apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "postgres.fullname" . }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ include "postgres.fullname" . }}
    template:
        metadata:
            labels:
                app: {{ include "postgres.fullname" . }}
        spec:
            containers:
                - name: postgres
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                  imagePullPolicy: {{ .Values.image.imagePullPolicy }}
                  ports:
                    - containerPort: 5432
                  envFrom:
                    - secretRef:
                        name: {{ include "postgres.fullname" . }}
                  volumeMounts:
                    - name: data
                      mountPath: /var/lib/postgresql/data
            volumes:
              - name: data
                {{- if .Values.pvc.enabled }}
                persistentVolumeClaim:
                  claimName: {{ include "postgres.fullname" . }}
                {{- else }}
                emptyDir: {}
                {{- end }}