{{- if .Values.pvc.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "postgres.fullname" . }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.pvc.size }}
    {{- if .Values.pvc.storageClassName }}
    storageClassName: {{ .Values.pvc.storageClassName }}
    {{- end }}
{{-end }}