image:
  repository: anhle3532/k8s-beginning
  tag: dev-39ef2b0
  pullPolicy: Always

replicaCount: 1

components:
  - name: server
    command: ["./k8s-beginning"]
    args:
      - "server"
      - "-c"
      - "/app/configs/config.yaml"
    service:
      enabled: true
      type: LoadBalancer
      httpPort: 8000
      grpcPort: 9000

  - name: worker
    command: ["./k8s-beginning"]
    args:
      - "worker"
      - "-c"
      - "/app/configs/config.yaml"
    service:
      enabled: false
