# Triggering re-run after network check
kafka:
  image: apache/kafka
  tag: 3.8.0
  replicaCount: 1
  clusterId: "re4L8ePWSU6y5u6r_kA07Q"
  service:
    type: ClusterIP
    port: 9092

console:
  image: docker.redpanda.com/redpandadata/console
  tag: latest
  service:
    type: NodePort
    port: 8080
    nodePort: 30080
