apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: kratos
          resources:
            requests: { cpu: 200m, memory: 256Mi }
            limits: { cpu: 500m, memory: 512Mi }
