apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-begining-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-begining-service
  template:
    metadata:
      labels:
        app: k8s-begining-service
    spec:
      containers:
        - name: k8s-begining-service
          image: anhle3532/k8s-begining-service:prod-latest
          env:
            - name: ENV
              value: "prod"
            - name: HTTP_PORT
              value: "8000"
            - name: GRPC_PORT
              value: "9000"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-begining-service
spec:
  selector:
    app: k8s-begining-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 9000
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-begining-service-http
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: 172.16.5.133
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-begining-service
                port:
                  number: 8000 # HTTP only
