apiVersion: v1
kind: Service
metadata:
  name: {{ include "seaweed.fullname" . }}
  labels:
    {{- include "seaweed.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.masterPort }}
      targetPort: master
      protocol: TCP
      name: master
    - port: {{ .Values.server.masterGrpcPort }}
      targetPort: master-grpc
      protocol: TCP
      name: master-grpc
    - port: {{ .Values.server.volumePort }}
      targetPort: volume
      protocol: TCP
      name: volume
    - port: {{ .Values.server.volumeGrpcPort }}
      targetPort: volume-grpc
      protocol: TCP
      name: volume-grpc
    - port: {{ .Values.server.filerPort }}
      targetPort: filer
      protocol: TCP
      name: filer
    - port: {{ .Values.server.filerGrpcPort }}
      targetPort: filer-grpc
      protocol: TCP
      name: filer-grpc
    - port: {{ .Values.server.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "seaweed.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
