apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{- include "redis.fullname" . }}
    labels:
        {{- include "redis.labels" . | indent 4}}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            {{- include "redis.labels" . | indent 8}}
    template:
        metadata:
            labels:
                {{- include "redis.labels" . | indent 8}}
        spec:
            containers:
                - name: redis
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  command:
                    - redis-server
                    - "--requirepass"
                    - "$(REDIS_PASSWORD)"
                    {{- if .Values.redis.appendonly }}
                    - "--appendonly"
                    - "yes"
                    {{- end }}
                  env:
                    - name: REDIS_PASSWORD
                      value: {{ .Values.redis.password }}
                  volumeMounts:
                    - name: redis-data
                      mountPath: /data
            volumes:
                - name: redis-data
                  {{- if .Values.persistence.enabled }}
                  persistentVolumeClaim:
                    claimName: {{ include "redis.fullname" . }}
                  {{- else }}
                  emptyDir: {}
                  {{- end }}