apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-beginning-dev
spec:
  project: default
  source:
    repoURL: https://github.com/anhle3532/k8s-devops.git
    targetRevision: HEAD
    path: apps/k8s-beginning
    helm:
      valueFiles:
        - values.yml
        - values-dev.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
