apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-qa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/besanh/k8s-devops.git
    targetRevision: main
    path: argocd/apps/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
