apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-begining-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/besanh/k8s-devops.git
    targetRevision: dev
    path: environments/dev
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-begining-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
