apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.27.0
    helm:
      values: |
        global:
          enabled: true

        server:
          # Production mode (not dev)
          dev:
            enabled: false
          
          # Standalone mode with Raft storage
          standalone:
            enabled: true
            config: |
              ui = true
              
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              
              storage "raft" {
                path = "/vault/data"
              }
              
              service_registration "kubernetes" {}
          
          # Persistent storage
          dataStorage:
            enabled: true
            size: 1Gi
          
          # Expose UI via NodePort
          service:
            type: NodePort
            nodePortConfiguration:
              nodePort: 30200
          
          # Resource limits
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m

        # Enable the injector for automatic secret injection
        injector:
          enabled: true
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m

        ui:
          enabled: true
          serviceType: NodePort
          serviceNodePort: 30200
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
