apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-beginning.fullname" . }}-dev-config
data:
  config.yaml: |
    app:
      name: k8s-beginning
      env: dev
    data:
      database:
        driver: postgres
        source: postgres://anh_admin:anh123@postgres.dev.svc.cluster.local:5432/anh_k8s_db?sslmode=disable
