image:
  repository: postgres
  tag: 16-alpine
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5432
  nodePort: 30432

replicaCount: 1

postgres:
  user: anh_admin
  password: "anh_db_password_123"
  db: anh_k8s_db

pvc:
  enabled: false
  size: 1Gi
  storageClassName: ""
