apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-beginning
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/besanh/k8s-devops.git
    targetRevision: main
    path: apps/dev/k8s-beginning
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
