apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: {{ .Values.kafka.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka

  template:
    metadata:
      labels:
        app: kafka

    spec:
      securityContext:
        fsGroup: 1001

      containers:
      - name: kafka
        image: "{{ .Values.kafka.image }}:{{ .Values.kafka.tag }}"
        imagePullPolicy: IfNotPresent

        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 512Mi

        ports:
        - name: kafka
          containerPort: 9092
        - name: controller
          containerPort: 9093

        env:
        - name: KAFKA_CFG_NODE_ID
          value: "1"

        - name: KAFKA_CFG_PROCESS_ROLES
          value: "broker,controller"

        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"

        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-0.kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"

        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"

        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"

        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-0.kafka.{{ .Release.Namespace }}.svc.cluster.local:9093"

        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"

        - name: KAFKA_KRAFT_CLUSTER_ID
          value: {{ .Values.kafka.clusterId | quote }}

        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"

        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"

        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"

        - name: KAFKA_CFG_LOG_DIRS
          value: "/bitnami/kafka/data"

        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"

        volumeMounts:
        - name: kafka-data
          mountPath: /bitnami/kafka/data

  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi